// <auto-generated />
namespace WpfApp1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_first_migratin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_first_migratin));
        
        string IMigrationMetadata.Id
        {
            get { return "202311072242499_add_first_migratin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
